"""auto

Revision ID: 13fff80e415a
Revises: 49137a75e3e9
Create Date: 2022-12-01 11:52:27.050951

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '13fff80e415a'
down_revision = '49137a75e3e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complexes', 'next_complex_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complexes', sa.Column('next_complex_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###