"""auto

Revision ID: 1e542c1a51ed
Revises: 6a88aa12ff7a
Create Date: 2022-12-01 17:13:48.127646

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1e542c1a51ed'
down_revision = '6a88aa12ff7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'created_at')
    # ### end Alembic commands ###