"""auto

Revision ID: 31c9634a4755
Revises: 7d1d3654e525
Create Date: 2022-12-07 09:37:58.347549

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '31c9634a4755'
down_revision = '7d1d3654e525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_checks', sa.Column('order_num', sa.Integer(), nullable=False))
    op.add_column('payment_checks', sa.Column('sum', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('payment_checks', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('payment_checks', sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('payment_checks', sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('payment_checks', sa.Column('customer_extra', sa.Integer(), nullable=False))
    op.add_column('payment_checks', sa.Column('payment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('payment_checks', sa.Column('payment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('payment_checks', sa.Column('rate_id', sa.Integer(), nullable=False))
    op.add_column('payment_checks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payment_checks', 'rates', ['rate_id'], ['id'])
    op.create_foreign_key(None, 'payment_checks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_checks', type_='foreignkey')
    op.drop_constraint(None, 'payment_checks', type_='foreignkey')
    op.drop_column('payment_checks', 'user_id')
    op.drop_column('payment_checks', 'rate_id')
    op.drop_column('payment_checks', 'payment_status')
    op.drop_column('payment_checks', 'payment_type')
    op.drop_column('payment_checks', 'customer_extra')
    op.drop_column('payment_checks', 'customer_email')
    op.drop_column('payment_checks', 'customer_phone')
    op.drop_column('payment_checks', 'currency')
    op.drop_column('payment_checks', 'sum')
    op.drop_column('payment_checks', 'order_num')
    # ### end Alembic commands ###