"""auto

Revision ID: 3dde74bdbbed
Revises: b06017023126
Create Date: 2022-11-26 16:22:51.258788

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3dde74bdbbed'
down_revision = 'b06017023126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sms_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('sms_call_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sms_call_code')
    op.drop_column('users', 'sms_message')
    # ### end Alembic commands ###