"""auto

Revision ID: 465a769584f9
Revises: cc9f407bd25e
Create Date: 2022-12-07 10:07:47.622756

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '465a769584f9'
down_revision = 'cc9f407bd25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###