"""auto

Revision ID: 49137a75e3e9
Revises: b33350383473
Create Date: 2022-12-01 11:41:49.194173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '49137a75e3e9'
down_revision = 'b33350383473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'number')
    # ### end Alembic commands ###