"""auto

Revision ID: 5b4ae1a85b2a
Revises: 31c9634a4755
Create Date: 2022-12-07 09:48:57.693326

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5b4ae1a85b2a'
down_revision = '31c9634a4755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_checks', 'customer_extra')
    op.drop_column('payment_checks', 'order_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_checks', sa.Column('order_num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payment_checks', sa.Column('customer_extra', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###