"""auto

Revision ID: 6518f819daec
Revises: f56f8e8fb2f5
Create Date: 2022-12-01 17:11:43.861631

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6518f819daec'
down_revision = 'f56f8e8fb2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'notification_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_time', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###