"""auto

Revision ID: 6685ad9356ae
Revises: 6e0697620dfe
Create Date: 2022-11-28 14:13:13.973461

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6685ad9356ae'
down_revision = '6e0697620dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complexes', sa.Column('number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'complexes', ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complexes', type_='unique')
    op.drop_column('complexes', 'number')
    # ### end Alembic commands ###