"""auto

Revision ID: 6a88aa12ff7a
Revises: 6b2f6fcc9417
Create Date: 2022-12-01 17:12:25.138437

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6a88aa12ff7a'
down_revision = '6b2f6fcc9417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###