"""auto

Revision ID: 6b2f6fcc9417
Revises: 6518f819daec
Create Date: 2022-12-01 17:11:55.283788

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6b2f6fcc9417'
down_revision = '6518f819daec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###