"""auto

Revision ID: 70a066435985
Revises: a54c21426c3e
Create Date: 2022-12-07 10:34:25.263202

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '70a066435985'
down_revision = 'a54c21426c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###