"""auto

Revision ID: 7d1d3654e525
Revises: 24f1b978b1c6
Create Date: 2022-12-07 09:27:09.321328

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7d1d3654e525'
down_revision = '24f1b978b1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_checks', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'payment_checks', ['order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_checks', type_='unique')
    op.drop_column('payment_checks', 'order_id')
    # ### end Alembic commands ###