"""empty message

Revision ID: 8e3167db7db7
Revises: bbeadc418c00
Create Date: 2022-12-20 17:38:24.699847

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8e3167db7db7'
down_revision = 'bbeadc418c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moods_id'), 'moods', ['id'], unique=False)
    op.add_column('users', sa.Column('last_entry', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('mood', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'moods', ['mood'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'mood')
    op.drop_column('users', 'last_entry')
    op.drop_index(op.f('ix_moods_id'), table_name='moods')
    op.drop_table('moods')
    # ### end Alembic commands ###