"""auto

Revision ID: 8f0d8e8b0332
Revises: a19c04676b46
Create Date: 2022-12-04 15:20:47.926661

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8f0d8e8b0332'
down_revision = 'a19c04676b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('payment_sign', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'payments', ['payment_sign'])
    op.create_unique_constraint(None, 'payments', ['payment_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'payment_sign')
    op.drop_column('payments', 'payment_id')
    # ### end Alembic commands ###