"""auto

Revision ID: a19c04676b46
Revises: d5a1944f8d11
Create Date: 2022-12-04 15:06:38.974406

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a19c04676b46'
down_revision = 'd5a1944f8d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###