"""auto

Revision ID: a54c21426c3e
Revises: 465a769584f9
Create Date: 2022-12-07 10:32:57.148426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a54c21426c3e'
down_revision = '465a769584f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###