"""auto

Revision ID: b4bd7ba4064f
Revises: 7bae87ecdaaa
Create Date: 2022-11-22 09:06:19.303268

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b4bd7ba4064f'
down_revision = '7bae87ecdaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###