"""auto

Revision ID: ca9a72534901
Revises: 8f0d8e8b0332
Create Date: 2022-12-07 09:22:20.062894

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ca9a72534901'
down_revision = '8f0d8e8b0332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###