"""auto

Revision ID: cc9f407bd25e
Revises: 5b4ae1a85b2a
Create Date: 2022-12-07 10:02:04.502134

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cc9f407bd25e'
down_revision = '5b4ae1a85b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###