"""auto

Revision ID: eb1e0c9dc5d1
Revises: 03f565711d3b
Create Date: 2022-12-08 20:37:41.244546

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'eb1e0c9dc5d1'
down_revision = '03f565711d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###