"""auto

Revision ID: f56f8e8fb2f5
Revises: 13fff80e415a
Create Date: 2022-12-01 12:33:45.081580

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f56f8e8fb2f5'
down_revision = '13fff80e415a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewed_complexes', sa.Column('viewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewed_complexes', 'viewed_at')
    # ### end Alembic commands ###