"""auto

Revision ID: fab0705f2fc8
Revises: 6685ad9356ae
Create Date: 2022-11-28 14:14:03.711438

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fab0705f2fc8'
down_revision = '6685ad9356ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewed_complexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complex_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['complex_id'], ['complexes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viewed_complexes_id'), 'viewed_complexes', ['id'], unique=False)
    op.create_table('viewed_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viewed_videos_id'), 'viewed_videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viewed_videos_id'), table_name='viewed_videos')
    op.drop_table('viewed_videos')
    op.drop_index(op.f('ix_viewed_complexes_id'), table_name='viewed_complexes')
    op.drop_table('viewed_complexes')
    # ### end Alembic commands ###