version: '3.7'

services:
  ci_postgres:
    env_file:
      - ./.env
    container_name: ci_postgres
    image: postgres:14.4-alpine
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/lib/postgresql/data/pg_log"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
    restart: on-failure
    volumes:
      - ./postgres_db/postgres/postgresql-data:/var/lib/postgresql/data
      - ./postgres_db/postgres/pginit/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  redis:
    image: redis:alpine
    volumes:
      - ./redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/etc/sysctl.conf:/usr/local/etc/redis/sysctl.conf
      - ./redis/data:/data

  app:
    build: ./ci_api
    container_name: ${APPNAME}-${VERSION}
    image: ${APPNAME}:${VERSION}
    env_file:
      - ./.env
    command: >
      sh -c "sleep 5 &&
             alembic upgrade head &&
             uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000"
    environment:
      POSTGRES_HOST: "ci_postgres"
      REDIS_DB: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
      - /var/www/ci_api/media:/app/media
      - ./payments:/app/payments
    depends_on:
      - ci_postgres
      - redis
    restart: on-failure

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4:6.10
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
#    ports:
#      - 5004:80
#    restart: on-failure
#    depends_on:
#      - ci_postgres
#      - app
