version: '3.7'

services:
  ci_postgres:
    env_file:
      - ./.env
    container_name: ci_postgres
    image: postgres:14.4-alpine
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/lib/postgresql/data/pg_log"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
    restart: on-failure
    volumes:
      - ./postgres_db/postgres/postgresql-data:/var/lib/postgresql/data
      - ./postgres_db/postgres/pginit/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  ci_api:
    build: ./ci_api
    env_file:
      - ./.env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000"
    environment:
      POSTGRES_HOST: "ci_postgres"
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
      - ./media:/app/media
      - ./payments:/app/payments
    depends_on:
      - ci_postgres
    restart: on-failure

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - '80:80'
#      - '8080:8080'
#      - '443:443'
#    volumes:
#      - ./nginx/config/:/etc/nginx/conf.d
##      - ./static:/www/data/static
#    depends_on:
#      - ci_api
#    restart: always
