version: '3.9'

services:
  ci_postgres:
    env_file:
      - ./ci_api/.env
    container_name: ci_postgres
    hostname: ci_postgres
    image: postgres:14.4-alpine
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/lib/postgresql/data/pg_log"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
    restart: on-failure
    volumes:
      - ./postgres_db/postgres/postgresql-data:/var/lib/postgresql/data
      - ./postgres_db/postgres/pginit/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  web:
    build: ./ci_api
    env_file:
      - ./ci_api/.env
    command: >
      sh -c "uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: "ci_postgres"
    volumes:
      - ./migrations:/app/migrations
      - ./media:/app/media
    depends_on:
      - ci_postgres
