name: ci_api_tests
on:
  pull_request:
    branches: [ main develop ]
  push:
    branches: [ main develop ]
jobs:
  create_docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start tests
        run: VERSION="test" APPNAME="test" docker-compose run --rm app pytest -k server tests/'
