name: ci_api_tests
on:
  push:
    branches: [ deskent ]

jobs:
  running_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          docker-compose -f docker-compose-test.yml up -d --build
      - name: Testing
        run: |
          docker-compose -f docker-compose-test.yml run --rm app pytest -k server tests/
      - name: End
        run: |
          docker-compose -f docker-compose-test.yml down
