name: ci_api_tests
on:
  pull_request:
    branches: [ main develop ]
  push:
    branches: [ main develop ]
jobs:
  running_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: VERSION="test" APPNAME="test" docker-compose run --rm app pytest -k server tests/'
#
#
#name: learn-github-actions
#run-name: ${{ github.actor }} is learning GitHub Actions
#on: [push]
#jobs:
#  check-bats-version:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '14'
#      - run: npm install -g bats
#      - run: bats -v
